cask_args appdir: '/Applications'

tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "ack"
brew "ag"
brew "coreutils"
brew "ctags"
brew "elixir"
brew "emacs"
brew "fasd"
brew "fontconfig"
brew "gcc"
brew "git-extras"
brew "httrack"
brew "hub"
brew "jq"
brew "lastpass-cli", args: ["with-pinentry"]
brew "node"
brew "parallel"
brew "pipenv"
brew "portmidi"
brew "ripgrep"
brew "ruby", link: true
brew "sdl"
brew "sdl_image"
brew "sdl_mixer"
brew "sdl_ttf"
brew "swig"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "watchman"
brew "zplug"
cask "adium"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "qutebrowser"
cask "spotify"
cask "xmind"
cask "xquartz"
