# Minimal test build - validates shell setup without Linuxbrew
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl git locales zsh \
    && rm -rf /var/lib/apt/lists/* \
    && locale-gen en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

ARG USERNAME=dev
RUN useradd -m -s /usr/bin/zsh -u 1001 $USERNAME

USER $USERNAME
WORKDIR /home/$USERNAME

# Clone dotfiles and set up shell
RUN git clone https://github.com/mshuffett/dotfiles.git .dotfiles \
    && ln -sf .dotfiles/zsh/zshenv.symlink .zshenv \
    && ln -sf .dotfiles/zsh/zshrc.symlink .zshrc \
    && ln -sf .dotfiles/zsh/p10k.zsh.symlink .p10k.zsh \
    && mkdir -p .cache/zsh4humans/v5 \
    && curl -fsSL "https://raw.githubusercontent.com/romkatv/zsh4humans/v5/z4h.zsh" > .cache/zsh4humans/v5/z4h.zsh

ENV TERM=xterm-256color
CMD ["zsh", "-l"]
