#!/bin/bash
set -ex
git clone https://github.com/mshuffett/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
git submodule init
git submodule update
sudo script/install # sudo for changing default shell
script/bootstrap
